from enum import Enum
from typing import NamedTuple

# --- TOKENS ENUM ---

class Tokens(Enum):
    # --- IGNORE ---
    
    COMMENT = "COMMENT"
    NEWLINE = "NEWLINE"
    WHITESPACE = "WHITESPACE"
    ILLEGAL = "ILLEGAL"
    EOF = "EOF"
    INDENT = "INDENT"
    DEDENT = "DEDENT"
    
    # --- MULTI CHAR OPERATORS ---
    
    OP_EQUAL_TO = "OP_EQUAL_TO"
    OP_LESS_THAN_EQ = "OP_LESS_THAN_EQ"
    OP_GREATER_THAN_EQ = "OP_GREATER_THAN_EQ"
    OP_INCREMENT = "OP_INCREMENT"
    OP_DECREMENT = "OP_DECREMENT"
    OP_ADDITION_ASSIGNMENT = "OP_ADDITION_ASSIGNMENT"
    OP_SUBSTRACTIONAL_ASSIGNMENT = "OP_SUBSTRACTIONAL_ASSIGNMENT"
    OP_MULTIPLICATIONAL_ASSIGNMENT = "OP_MULTIPLICATIONAL_ASSIGNMENT"
    OP_DIVISIONAL_ASSIGNMENT = "OP_DIVISIONAL_ASSIGNMENT"
    
    # --- VARIABLE MODIFIERS ---
    
    VM_ATOMIC = "VM_ATOMIC"
    VM_ALLOC = "VM_ALLOC"
    VM_VOLATILE = "VM_VOLATILE"
    VM_UNSIGNED = "VM_UNSIGNED"
    VM_CONST = "VM_CONST"
    
    # --- DATATYPES ---
    
    DT_INT = "DT_INT"
    DT_FLOAT = "DT_FLOAT"
    DT_CHAR = "DT_CHAR"
    DT_BOOL = "DT_BOOL"
    DT_BYTE = "DT_BYTE"
    DT_PTR = "DT_PTR"
    DT_NONE = "DT_NONE"
    
    # --- KEYWORDS ---
    
    KW_ADDR = "KW_ADDR"
    KW_AT = "KW_AT"
    KW_FREE = "KW_FREE"
    KW_NULL = "KW_NULL"
    KW_STRUCT = "KW_STRUCT"
    KW_ENUM = "KW_ENUM"
    KW_TYPEDEF = "KW_TYPEDEF"
    KW_AS = "KW_AS"
    KW_ECHO = "KW_ECHO"
    KW_IF = "KW_IF"    
    KW_ELIF = "KW_ELIF"
    KW_ELSE = "KW_ELSE"
    KW_WHILE = "KW_WHILE"
    KW_BREAK = "KW_BREAK"
    KW_CONTINUE = "KW_CONTINUE"
    KW_RETURN = "KW_RETURN"
    KW_PASS = "KW_PASS"
    KW_AND = "KW_AND"
    KW_OR = "KW_OR"
    KW_NOT = "KW_NOT"
    LITERAL_BOOLEAN_TRUE = "LITERAL_BOOLEAN_TRUE"
    LITERAL_BOOLEAN_FALSE = "LITERAL_BOOLEAN_FALSE"
    KW_BITWISE_AND = "KW_BITWISE_AND"
    KW_BITWISE_OR = "KW_BITWISE_OR"
    KW_BITWISE_XOR = "KW_BITWISE_XOR"
    KW_BITWISE_NAND = "KW_BITWISE_NAND"
    KW_BITWISE_NOT = "KW_BITWISE_NOT"
    KW_BITWISE_SHIFT_LEFT = "KW_BITWISE_SHIFT_LEFT"
    KW_BITWISE_SHIFT_RIGHT = "KW_BITWISE_SHIFT_RIGHT"
    KW_IMPORT = "KW_IMPORT"
    KW_FROM = "KW_FROM"
    KW_SIZEOF = "KW_SIZEOF"
    
    # --- LITERALS ---
    
    FLOAT_LITERAL = "FLOAT_LITERAL"
    INTEGER_LITERAL = "INTEGER_LITERAL"
    STRING_LITERAL = "STRING_LITERAL"
    CHARACTER_LITERAL = "CHARACTER_LITERAL"
    BINARY_LITERAL = "BINARY_LITERAL"
    HEXADECIMAL_LITERAL = "HEXADECIMAL_LITERAL"
    IDENTIFIER = "IDENTIFIER"
    
    # --- OPERATORS ---
    
    OP_ADDITION = "OP_ADDITION"
    OP_SUBTRACTION = "OP_SUBTRACTION"
    OP_MULTIPLICATION = "OP_MULTIPLICATION"
    OP_DIVISION = "OP_DIVISION"
    OP_MODULO = "OP_MODULO"
    OP_ASSIGNMENT = "OP_ASSIGNMENT"
    OP_LESS_THAN = "OP_LESS_THAN"
    OP_GREATER_THAN = "OP_GREATER_THAN"
    PUNC_COMMA = "PUNC_COMMA"
    PUNC_DOT = "PUNC_DOT"
    PUNC_COLON = "PUNC_COLON"
    PUNC_SEMICOLON = "PUNC_SEMICOLON"
    PUNC_NULLABLE = "PUNC_NULLABLE"
    PUNC_PIPE = "PUNC_PIPE"
    PUNC_LEFT_PARENTHESIS = "PUNC_LEFT_PARENTHESIS"
    PUNC_RIGHT_PARENTHESIS = "PUNC_RIGHT_PARENTHESIS"
    PUNC_LEFT_BRACKET = "PUNC_LEFT_BRACKET"
    PUNC_RIGHT_BRACKET = "PUNC_RIGHT_BRACKET"
    PUNC_LEFT_BRACE = "PUNC_LEFT_BRACE"
    PUNC_RIGHT_BRACE = "PUNC_RIGHT_BRACE"
    
    
# --- TOKEN STRUCT ---

class TokenStruct(NamedTuple):
    token: Tokens
    lexeme: int | str
    line: int
    col: int
    
    